"""empty message

Revision ID: 3689aea354c3
Revises: 1fe45e766932
Create Date: 2026-06-18 17:12:08.160960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3689aea354c3'
down_revision = '1fe45e766932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_bowl_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saved_bowl_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name_snapshot', sa.String(length=100), nullable=False),
    sa.Column('category_name_snapshot', sa.String(length=50), nullable=False),
    sa.Column('category_slug_snapshot', sa.String(length=50), nullable=False),
    sa.Column('color_key_snapshot', sa.String(length=50), nullable=False),
    sa.Column('shape_family_snapshot', sa.String(length=50), nullable=False),
    sa.Column('visual_pattern_snapshot', sa.String(length=50), nullable=False),
    sa.Column('sort_order_snapshot', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ingredient_categories.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['saved_bowl_id'], ['saved_bowls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_bowl_ingredients')
    # ### end Alembic commands ###
